{% set version = "2.1.4" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-lmperm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lmPerm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lmPerm/lmPerm_{{ version }}.tar.gz
  sha256: 3b1668bf72cb3252bad8ce684b243b3a4c236d365581e7c80c24c6838b921916

build:
  number: 1

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ stdlib("c") }}    # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem  # [win]
    - {{ posix }}make
    - {{ posix }}sed  # [win]
    - {{ posix }}coreutils  # [win]
    - {{ posix }}zip  # [win]

  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('lmPerm')"  # [not win]
    - "\"%R%\" -e \"library('lmPerm')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/lmPerm/index.html
  dev_url: https://github.com/mtorchiano/lmPerm
  doc_url: https://cran.r-project.org/web/packages/lmPerm/lmPerm.pdf
  license: GPL-2.0-or-later
  summary: Linear model functions using permutation tests.
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# The original CRAN metadata for this package was:

# Package: lmPerm
# Version: 2.1.0
# Title: Permutation Tests for Linear Models
# Author: Bob Wheeler <bwheelerg@gmail.com>, Marco Torchiano <marco.torchiano@polito.it>
# Maintainer: Marco Torchiano <marco.torchiano@polito.it>
# Imports: stats
# Description: Linear model functions using permutation tests.
# License: GPL (>= 2)
# URL: https://github.com/mtorchiano/lmPerm
# Repository: CRAN
# NeedsCompilation: yes
# Suggests: testthat
# Packaged: 2016-08-02 00:00:18 UTC; mtk
# Date/Publication: 2016-08-02 13:20:03

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
